export type ReleaseNote = {
  version: string;
  date: string;
  title: string;
  items: string[];
  current?: boolean;
};

export const APP_RELEASE_NOTES: ReleaseNote[] = [
  {
    version: "v1.11",
    title: "Optimierte Live-Aktualisierung",
    date: "2026-08-20",
    current: true,
    items: [
      "Öffentliche Live-Ansicht nutzt neu ein kleines Meta-Dokument zur Prüfung statt bei jeder Aktualisierung den kompletten Live-Stand zu laden.",
      "Admin-App erhöht bei jeder Live-Veröffentlichung eine liveVersion; Zuschauer laden den vollständigen Live-Stand nur, wenn sich diese Version geändert hat.",
      "Vor dem Rennen mit reiner Startliste bleibt die Zuschauer-Prüfung sparsam: manuell oder Sicherheitsprüfung einmal pro Stunde.",
      "Während Motos, Halbfinals oder Finals sichtbar sind, prüft die Zuschaueransicht alle 30 Sekunden nur die kleine Live-Meta-Version.",
      "Wenn der Browser-Tab im Hintergrund ist, wird die Prüfung automatisch langsamer, um Datenverbrauch und Firestore-Reads zu reduzieren.",
      "Live-Ansicht zeigt Aktualisierungsmodus, letzte Prüfung und erkannte Live-Version an.",
      "Keine Änderung an Rennlogik, Einteilung, Punktewertung, Login oder Online-Speicher für Admin-Daten.",
    ],
  },
  {
    version: "v1.10",
    title: "Eventbasierte Live-Aktualisierung",
    date: "2026-08-20",
    current: false,
    items: [
      "Admin-App veröffentlicht Live-Daten nicht mehr in einem fixen Sekundenintervall.",
      "Sobald der letzte Fahrer eines Motos, Halbfinals oder Finals im Zieleinlauf erfasst ist, wird der Live-Stand automatisch online aktualisiert.",
      "Beim Erstellen von Motos, Finals oder einer manuellen Rangliste wird ein aktives Live-Rennen automatisch neu veröffentlicht.",
      "Vor dem Rennen, wenn nur die Startliste sichtbar ist, aktualisiert die Zuschaueransicht nur manuell oder als Sicherheitsprüfung einmal pro Stunde.",
      "Während Motos/Finals vorhanden sind, aktualisiert die Zuschaueransicht automatisch alle 30 Sekunden.",
      "Wenn Teilnehmer vor der Moto-Erstellung erfasst oder geändert werden und das Rennen live ist, sendet die Admin-App die aktualisierte Startliste automatisch nach.",
      "Beim Sprung zum nächsten Lauf scrollt die App direkt zum Zieleinlauf-Eingabebereich.",
      "Keine Änderung an Rennlogik, Einteilung, Punktewertung, Login oder Online-Speicherstruktur.",
    ],
  },
  {
    version: "v1.9",
    title: "Live-Takt, Startliste & Laufnavigation",
    date: "2026-08-20",
    current: false,
    items: [
      "App-Version im Banner auf v1.9 gesetzt.",
      "Beim Abschluss eines Motos springt die Ansicht direkt zum nächsten Zieleinlauf-Eingabebereich statt zu hoch an den Abschnittsanfang.",
      "Beim Live-Schalten ist der Live-Aktualisierungstakt auswählbar: 5, 10, 30, 60, 90 oder 180 Sekunden.",
      "Admin-Live-Veröffentlichung und Zuschaueransicht verwenden den gewählten Aktualisierungstakt.",
      "Wenn ein Rennen live ist, aber Motos noch nicht erstellt wurden, zeigt die Zuschaueransicht die aktuelle Startliste nach Kategorien.",
      "4. Moto bleibt weiterhin nur im Finalblock; Rennlogik, Einteilung und Rangpunkte wurden nicht verändert.",
    ],
  },
  {
    version: "v1.16.9",
    title: "Live-Ablauf & automatische Laufnavigation",
    date: "2026-08-20",
    current: false,
    items: [
      "Abgeschlossene Motos und Finalläufe klappen im Rennbetrieb automatisch zu.",
      "Nach vollständig gespeichertem Resultat springt die App automatisch zum nächsten offenen Lauf.",
      "Der aktuelle Lauf wird blau hervorgehoben; der nächste Lauf für den Starthelfer wird rot mit ans Gate markiert.",
      "4. Moto bleibt ausschliesslich im Finalblock und wird zusammen mit den A-Finals am Schluss gefahren.",
      "Die öffentliche Live-Ansicht zeigt nach vorhandenen Resultaten automatisch Resultate statt Startliste/Gateplätze.",
      "Die Live-Ansicht hebt den laufenden Lauf und den nächsten Lauf ans Gate farblich hervor.",
      "Rennlogik, Einteilung, Halbfinal-/Final-Reihenfolge und DNS-/Rangpunkte-Regeln wurden im Code nochmals gegen die aktuelle Logik geprüft.",
    ],
  },
  {
    version: "v1.16.8",
    title: "Spezial-Kategorie bereinigt",
    date: "2026-08-20",
    current: false,
    items: [
      "Das separate Cruiser-Häkchen im Teilnehmerformular wird nicht mehr angezeigt.",
      "Cruiser wird nur noch über das Auswahlfeld Spezial-Kategorie gesetzt.",
      "Plausch 1, Plausch 2, Plausch 3 und Cruiser sind damit an einer Stelle auswählbar.",
      "Bestehende Cruiser-Daten bleiben erhalten; nur die doppelte Darstellung wurde entfernt.",
      "Keine Änderung an Rennlogik, Teilnehmerdaten, Online-Speicher oder Live-Ansicht.",
    ],
  },
  {
    version: "v1.16.7",
    title: "Plausch-Kategorien & Finalblock-Reihenfolge",
    date: "2026-08-20",
    current: false,
    items: [
      "Neue Spezial-Kategorien Plausch 1, Plausch 2 und Plausch 3 ergänzt.",
      "Plausch-Kategorien sind wie Cruiser separat auswählbar und werden separat gewertet.",
      "Plausch 1–3 starten in der Kategorienreihenfolge immer vor allen regulären Alterskategorien.",
      "Cruiser startet nicht mehr ganz am Schluss, sondern direkt vor Boys 16+ / Girls 17+.",
      "Bei Kategorien mit 1–8 Fahrern wird der 4. Moto im Finalblock geführt und zusammen mit den A-Finals am Schluss angezeigt.",
      "Finals-PDF und öffentliche Live-Ansicht übernehmen die neue Finalblock-Reihenfolge.",
      "Renn-Reglement wurde mit Plausch-Kategorien, Cruiser-Reihenfolge und 4.-Moto-Finalblock ergänzt.",
      "Keine Änderung an Login, Online-Speicher oder Resultatberechnung.",
    ],
  },
  {
    version: "v1.16.6",
    title: "Final-Darstellung & Halbfinal-Freischaltung",
    date: "2026-08-20",
    current: false,
    items: [
      "C- und D-Finals werden bei Halbfinal-Kategorien nicht mehr sofort mit den Halbfinals angezeigt.",
      "Nach vollständig erfassten Halbfinalresultaten werden D-, C-, B- und A-Finals gemeinsam über Finals freischalten erzeugt.",
      "Die Final-Darstellung ist im Rennbetrieb nach Ablauf sortiert: zuerst D-, C- und B-Finals je Kategorie, danach alle A-Finals gesammelt am Schluss.",
      "Finals-PDF und öffentliche Live-Ansicht übernehmen die gleiche Reihenfolge mit A-Finals am Schluss.",
      "Renn-Reglement in der App wurde mit der neuen Freischalt- und Darstellungsregel ergänzt.",
      "Keine Änderung an Motos, Teilnehmerlogik, Login oder Online-Speicher.",
    ],
  },
  {
    version: "v1.16.5",
    title: "Halbfinal-Logik & Renn-Reglement",
    date: "2026-08-20",
    current: false,
    items: [
      "Maximal 32 Teilnehmer pro Kategorie/Laufgruppe erlaubt; zu grosse Kategorien werden mit klarer Fehlermeldung blockiert.",
      "Ab 20 Teilnehmern werden automatisch zwei Halbfinals für die besten 16 Fahrer nach den Motos erstellt.",
      "Bei 20–24 Teilnehmern fahren die restlichen Fahrer direkt C-Final; bei 25–32 Teilnehmern werden die restlichen Fahrer auf C- und D-Final verteilt.",
      "Nach erfassten Halbfinalresultaten können A- und B-Finals über den neuen Button A/B-Finals erstellen erzeugt werden.",
      "DNS in einem Final-/Endresultat wird nicht mehr in der Race-Rangliste geführt und erhält keine Gesamtwertungspunkte.",
      "Die App-Seite Renn-Reglement wurde mit einer vollständigen Übersicht der aktuellen Rennlogik ergänzt.",
    ],
  },
  {
    version: "v1.16.4",
    title: "Automatische Live-Aktualisierung",
    date: "2026-08-18",
    current: false,
    items: [
      "Ein live veröffentlichtes aktuelles Rennen wird im Admin-Rennbetrieb automatisch alle 30 Sekunden veröffentlicht/aktualisiert.",
      "Der manuelle Button bleibt als Jetzt live aktualisieren erhalten, ist aber im Normalbetrieb nicht mehr nötig.",
      "Auf der Rennseite wird angezeigt, dass die automatische Live-Aktualisierung aktiv ist.",
      "Beim Race abschliessen fragt die App neu, ob die öffentliche Live-Ansicht direkt beendet werden soll.",
      "Wenn die Live-Ansicht nach Race-Abschluss weiter aktiv bleibt, wird sie weiterhin automatisch aktualisiert.",
      "Keine Änderung an Rennlogik, Teilnehmerlogik oder Resultatberechnung.",
    ],
  },
  {
    version: "v1.16.3",
    title: "Öffentliche Live-Rennansicht",
    date: "2026-08-18",
    current: false,
    items: [
      "Öffentliche Zuschaueransicht ohne Login über den Link #live ergänzt.",
      "Auf der Rennseite kann das aktuell geöffnete Rennen live veröffentlicht, aktualisiert oder beendet werden.",
      "Die Live-Ansicht lädt automatisch alle 30 Sekunden neu und zeigt nur Motos, Startlisten, Resultate, Finals und Finalresultate des aktiven Rennens.",
      "Teilnehmer-Hauptdatenbank, Gesamtwertung, Backups, Speicherfunktionen, Bearbeiten-Buttons und interne IDs bleiben in der Live-Ansicht verborgen.",
      "Beim Online-Speichern wird ein bereits live veröffentlichtes aktuelles Rennen automatisch mit aktualisiert.",
      "Login-Startseite erhält einen Button Zuschaueransicht öffnen.",
      "Neue Firestore-Regeln trennen private App-Daten von öffentlich lesbaren Live-Renn-Daten.",
      "Keine Änderung an Rennlogik, Teilnehmerlogik oder Resultatberechnung.",
    ],
  },
  {
    version: "v1.16.2",
    title: "Login-Weiterleitung korrigiert",
    date: "2026-08-18",
    current: false,
    items: [
      "Fehler korrigiert, bei dem der Login erfolgreich geprüft wurde, die App danach aber auf der Login-Startseite stehen blieb.",
      "Der Online-Status wird nach dem Login jetzt mit der frisch erhaltenen Firebase-Sitzung geprüft, ohne die Anmeldung versehentlich zurückzusetzen.",
      "Nach erfolgreicher Anmeldung wird direkt die geschützte App-Startseite angezeigt.",
      "Fehlermeldungen beim Login bleiben sichtbar, falls E-Mail, Passwort oder Firebase-Konfiguration nicht stimmen.",
      "Keine Änderung an Rennlogik, Teilnehmerlogik oder Resultatberechnung.",
    ],
  },
  {
    version: "v1.16.1",
    title: "Login bei jedem Start",
    date: "2026-08-18",
    current: false,
    items: [
      "Die App zeigt bei jedem Öffnen, Neuladen oder nach dem Schliessen wieder zuerst die Login-Startseite.",
      "Eine frühere Firebase-Anmeldung wird nicht mehr automatisch wiederhergestellt.",
      "Die eigentliche App bleibt vollständig ausgeblendet, bis der Login erfolgreich ist.",
      "Login-Token werden nur während der aktuellen Nutzung im App-State gehalten und nicht dauerhaft im Browser gespeichert.",
      "Nach Abmelden oder Neuladen ist wieder ein Login mit E-Mail und Passwort nötig.",
      "Keine Änderung an Rennlogik, Teilnehmerlogik oder Resultatberechnung.",
    ],
  },
  {
    version: "v1.16.0",
    title: "Login-Startseite",
    date: "2026-08-18",
    current: false,
    items: [
      "Beim Öffnen der App erscheint zuerst eine geschützte Startseite mit Header-Banner und Anmeldefenster.",
      "Die eigentliche App, Startseite, Rennen, Teilnehmer, Resultate und Speicherfunktionen werden erst nach erfolgreichem Firebase Login angezeigt.",
      "Während eine vorhandene Anmeldung geprüft wird, zeigt die App nur den Login-Bereich mit Hinweis Anmeldung wird geprüft.",
      "Nach dem Abmelden wird die App wieder vollständig ausgeblendet und nur die Login-Startseite angezeigt.",
      "Header-Banner bleibt sichtbar; Rennlogik, Teilnehmerlogik und Resultatberechnung wurden nicht geändert.",
    ],
  },
  {
    version: "v1.15.9",
    title: "Firebase Login und geschützte Online-Daten",
    date: "2026-08-18",
    current: false,
    items: [
      "Firebase Login mit E-Mail und Passwort ergänzt.",
      "Startseite zeigt im Speicherbereich den Status Angemeldet als ... oder Nicht angemeldet.",
      "Abmelden-Button ergänzt; nach dem Abmelden sind Online speichern, Online laden und Online-Backups gesperrt.",
      "Online-Speicherzugriffe senden ein Firebase Auth ID Token an Firestore REST.",
      "Gespeicherte Anmeldung wird automatisch erneuert, solange ein gültiger Refresh Token vorhanden ist.",
      "Anleitung für Firebase Authentication und sichere Firestore-Regeln liegt als Zusatzdatei bei.",
      "Keine Änderung an Rennlogik, Teilnehmerlogik oder Resultatberechnung.",
    ],
  },
  {
    version: "v1.15.8",
    title: "Dublettenhilfe und Plate-Historie",
    date: "2026-08-18",
    current: false,
    items: [
      "Beim Erfassen eines Teilnehmers in der Hauptdatenbank werden während der Namenseingabe ähnliche bereits gespeicherte Teilnehmer angezeigt.",
      "Die Dublettenhilfe zeigt Name, Startnummer, Jahrgang, Geschlecht, Verein, Ähnlichkeitswert und Teilnehmer-ID an.",
      "Ein erkannter bestehender Teilnehmer kann direkt zur Bearbeitung geöffnet werden, damit keine unnötige Dublette entsteht.",
      "Wird eine Startnummer/Plate geändert, bleibt die alte Plate in bereits abgeschlossenen Rennen in gespeicherten Motos, Resultaten und Finals erhalten.",
      "Zukünftige und noch offene Rennen verwenden weiterhin die neu gespeicherte Plate.",
      "Keine Änderung an Rennlogik, Punkteberechnung oder Finalerstellung.",
    ],
  },
  {
    version: "v1.15.7",
    title: "Online-Speichern als Standard",
    date: "2026-08-18",
    current: false,
    items: [
      "Obere Backup-Warnzeile wurde vollständig entfernt; Speicher- und Backup-Funktionen liegen nur noch im Bereich Speicher auf der Startseite.",
      "Status-Chips Ungespeichert und Backup empfohlen wurden aus dem Header-Banner entfernt.",
      "Der Button Speichern im Rennblatt speichert jetzt online statt ein lokales Datei-Backup zu erzeugen.",
      "Der Speichern-Button im Rennblatt ist grün, wenn der aktuelle Stand online gespeichert ist, und orange, sobald Änderungen offen sind.",
      "Backup erstellen legt den aktuellen Stand online ab, erstellt ein beschriftetes Online-Backup und lädt zusätzlich eine lokale Backup-Datei herunter.",
      "Beim Backup-Laden kann weiterhin zwischen Online-Backup-Liste und lokaler Backup-Datei gewählt werden.",
      "Keine Änderung an Rennlogik, Teilnehmerlogik oder Resultatberechnung.",
    ],
  },
  {
    version: "v1.15.6",
    title: "Speicher-Dashboard vereinfacht",
    date: "2026-08-18",
    current: false,
    items: [
      "Obere Backup-Warnung verwendet jetzt den Button Online speichern statt Backup jetzt erstellen.",
      "Speicher-Dashboard optisch aufgeräumt und auf drei Hauptaktionen reduziert: Online speichern, letzten Online-Stand laden und Online-Backup erstellen.",
      "Datei-Backup, Datei-Import und zusätzliche Statusprüfung sind in weitere Speicheroptionen ausgelagert.",
      "Online-Backups bleiben als sichtbare Liste erhalten und können weiterhin direkt per Button geladen werden.",
      "Statuskarten für Online-Stand, letzte Speicherung und lokalen/Online-Vergleich wurden kompakter dargestellt.",
      "Keine Änderung an Rennlogik, Teilnehmerlogik oder Resultatberechnung.",
    ],
  },
  {
    version: "v1.15.5",
    title: "Online-Speicher-Dashboard und Backup-Liste",
    date: "2026-08-18",
    current: false,
    items: [
      "Startseite zeigt den Speicherbereich neu als klareres Dashboard.",
      "Buttons für Online-Speichern, Online-Laden, Online-Backup und Datei-Backup wurden verständlicher benannt.",
      "Online-Backups werden direkt als sichtbare Liste nach Datum angezeigt.",
      "Online-Backups können jetzt direkt über einen Button in der Liste geladen werden; keine Nummerneingabe mehr nötig.",
      "Warnungen vor dem Wiederherstellen wurden deutlicher formuliert und zeigen den Ablauf mit automatischem Sicherheitsbackup.",
      "Rennlogik, Teilnehmerlogik und Resultatberechnung bleiben unverändert.",
    ],
  },
  {
    version: "v1.15.4",
    title: "Online-Status und Online-Backups",
    date: "2026-08-18",
    current: false,
    items: [
      "Startseite zeigt den letzten Online-Speicherzeitpunkt und ob Online-Daten vorhanden sind.",
      "Button Online-Status prüfen ergänzt, inklusive Online-Backup-Liste.",
      "Online laden prüft vor dem Laden, ob lokale Daten neuer sind, und bietet Laden, lokales Hochladen oder Abbrechen an.",
      "Online laden ersetzt lokale Daten nur nach klarer Warnung und erstellt vorher automatisch ein Datei-Sicherheitsbackup.",
      "Beschriftete Online-Backups können erstellt und später nach Datum sortiert ausgewählt und geladen werden.",
      "Es werden bis zu 20 Online-Backups im Index geführt; ältere Backups werden automatisch aus der Auswahl entfernt.",
      "Lokaler Speicher und Datei-Backup bleiben unverändert aktiv.",
    ],
  },
  {
    version: "v1.15.3",
    title: "Firestore-Datenbank-ID default",
    date: "2026-08-18",
    current: false,
    items: [
      "Online-Speicher verwendet neu die Firestore-Datenbank-ID default ohne Klammern.",
      "Damit passt die App zu der in Google Cloud erstellten benannten Datenbank default.",
      "Optional kann die Datenbank-ID über VITE_FIREBASE_DATABASE_ID gesetzt werden.",
      "Online speichern/laden, lokaler Speicher und Datei-Backup bleiben unverändert.",
    ],
  },
  {
    version: "v1.15.2",
    title: "Firebase-Konfiguration über Vercel Environment Variables",
    date: "2026-08-18",
    current: false,
    items: [
      "Firebase API Key und Projektwerte werden nicht mehr direkt im GitHub-Repository gespeichert.",
      "Firebase-Konfiguration wird über Vercel Environment Variables geladen.",
      "GitHub Secret-Scanning-Warnungen für src/config/firebaseConfig.ts werden dadurch künftig vermieden.",
      "Online speichern/laden bleibt unverändert vorbereitet; Firestore muss im Firebase-Projekt als (default)-Datenbank erstellt sein.",
      "Lokaler Speicher und Datei-Backup bleiben unverändert aktiv.",
    ],
  },
  {
    version: "v1.15.1",
    title: "Online-Speicher aktiviert",
    date: "2026-08-18",
    current: false,
    items: [
      "Firebase-Projekt bmx-race-manager in der App-Konfiguration aktiviert.",
      "Online speichern und Online laden verwenden jetzt Firestore REST und komplette App-Daten.",
      "Der Online-Speicher nutzt eine Chunk-Speicherung, damit auch grössere Backup-Daten nicht an der Firestore-Dokumentgrösse scheitern.",
      "Lokaler Speicher und Datei-Backup bleiben unverändert als Sicherheit erhalten.",
      "Beim Online-Laden wird weiterhin zuerst ein Sicherheitsbackup erstellt und erst nach Bestätigung lokal ersetzt.",
    ],
  },
  {
    version: "v1.15.0",
    title: "Online-Speicher vorbereitet",
    date: "2026-08-18",
    current: false,
    items: [
      "Firebase-Konfigurationsdatei ergänzt, damit der Online-Speicher später ohne App-Umbau aktiviert werden kann.",
      "Online-Speicher-Utility über Firestore REST vorbereitet; es benötigt keine zusätzlichen npm-Pakete.",
      "Auf der Startseite wurden die Buttons Online speichern, Online laden, Backup erstellen und Backup importieren vorbereitet.",
      "Der lokale Speicher bleibt unverändert aktiv und dient weiterhin als Sicherheit.",
      "Backup erstellen erzeugt weiterhin eine komplette JSON-Datei mit allen Rennen, Teilnehmern, Resultaten und Einstellungen.",
    ],
  },
  {
    version: "v1.14.6",
    title: "Teilnehmer-Auswahlbuttons bereinigt",
    date: "2026-08-18",
    current: false,
    items: [
      "Im Bereich Teilnehmer in dieser Rennserie / diesem Rennen wurden die Race-Alle-Auswahlbuttons entfernt.",
      "Alle Kategorie-auswählen-Buttons innerhalb der Kategorien wurden entfernt.",
      "Die Auswahl der Fahrer erfolgt weiterhin direkt über die Race-Checkboxen R1, R2, R3 und R4 in der Tabelle.",
      "Keine Änderung an Teilnehmerdaten, Race-Zuordnung, Resultaten, Motos, Gates oder Backups.",
    ],
  },
  {
    version: "v1.14.5",
    title: "Teilnehmerliste übersichtlicher",
    date: "2026-08-18",
    current: false,
    items: [
      "Im Bereich Teilnehmer in dieser Rennserie / diesem Rennen wurden die Kategorie-Auswahlbuttons entfernt.",
      "Die Filterbuttons Alle, Race ausgewählt, Race offen, Fehlende Angaben, Doppelte Nummern und Cruiser sind jetzt gleich hoch und optisch einheitlich.",
      "Die Suche und die Filterbuttons wurden getrennt angeordnet, damit die Ansicht auf dem iPad ruhiger und besser bedienbar bleibt.",
      "Keine Änderung an Teilnehmerdaten, Race-Zuordnung, Resultaten, Motos, Gates oder Backups.",
    ],
  },
  {
    version: "v1.14.4",
    title: "Teilnehmer direkt im Rennen erfassen und auswählen",
    date: "2026-08-18",
    current: false,
    items: [
      "Im Teilnehmerbereich eines Rennens kann jetzt direkt ein neuer Teilnehmer erfasst werden, ohne zurück ins Hauptmenü zu wechseln.",
      "Neue Teilnehmer erhalten weiterhin automatisch eine stabile Teilnehmer-ID und werden direkt dem aktuell gewählten Race zugeordnet.",
      "Die Teilnehmerauswahl wurde übersichtlicher nach Kategorien gruppiert.",
      "Teilnehmer können per Suche, Kategorie-Filter, Mehrfachauswahl oder Kategorie-Schnellaktion zum aktuellen Race hinzugefügt werden.",
      "Der Teilnehmerlisten-Filter zeigt neu auch nur ausgewählte oder noch offene Teilnehmer für das aktuelle Race an.",
      "Nach bereits erstellten Motos bleibt die bestehende Notfall-Nachmeldung zuständig, damit Gate-Zuteilungen geschützt bleiben.",
    ],
  },
  {
    version: "v1.14.2",
    title: "Buildfix Nachmeldungen",
    date: "2026-08-17",
    current: false,
    items: [
      "TypeScript-Buildfehler in der Nachmelde-Auswahl korrigiert.",
      "Teilnehmer nachträglich hinzufügen verwendet intern nun eine einheitlich typisierte Auswahl.",
      "Keine Änderung an Rennlogik, Gates, Motos, Resultaten oder bestehenden Daten.",
    ],
  },
  {
    version: "v1.14.1",
    title: "Gate-Anzeige und Nachmeldungen",
    date: "2026-08-17",
    current: false,
    items: [
      "In den Moto- und Final-Startlisten wird links von Plate neu die Spalte Gate angezeigt.",
      "Unter Notfall / Reparatur gibt es neu Teilnehmer nachträglich hinzufügen.",
      "Nachgemeldete Teilnehmer werden zuerst in freie Gate-Plätze ihrer Kategorie gesetzt, ohne bestehende Fahrer zu verschieben.",
      "Wenn eine Kategorie durch die Nachmeldung mehr Fahrer hat als die bestehenden Moto-Gruppen aufnehmen können, fragt die App nach und erstellt nur diese Kategorie neu.",
      "Motos anderer Kategorien bleiben bei einer Nachmeldung unverändert.",
    ],
  },
  {
    version: "v1.14.0",
    title: "Gesamtwertung mit Teilnehmerfilter",
    date: "2026-07-30",
    current: false,
    items: [
      "Beim Erstellen der Gesamtwertung fragt die App neu, ob alle Teilnehmer mit Resultat oder nur Teilnehmer mit genügend Rennen angezeigt werden sollen.",
      "Der Filter richtet sich nach der Einstellung, wie viele Rennen für die Gesamtwertung zählen.",
      "Teilnehmer mit zu wenigen Rennen können dadurch auf Wunsch aus der Gesamtwertung ausgeblendet werden.",
      "Rennresultate und bestehende Daten werden nicht verändert; es wird nur die erzeugte Gesamtwertung gefiltert.",
    ],
  },
  {
    version: "v1.13.9",
    title: "Bugfix Manuelle Rangliste sichtbar",
    date: "2026-07-30",
    current: false,
    items: [
      "Beim Klick auf Manuelle Rangliste wird der Eingabebereich nun direkt auf der Rennseite angezeigt.",
      "Die manuelle Rangliste bleibt unabhängig von Motos/Heats und zeigt alle Teilnehmer einer Kategorie in einer Kachel.",
      "Hinweistexte für fehlende Renninformationen wurden an die manuelle Rangliste angepasst.",
      "Rangliste speichern erzeugt weiterhin die gewohnten Resultate für Resultate-PDF und Gesamtwertung.",
    ],
  },
  {
    version: "v1.13.8",
    title: "Manuelle Rangliste pro Kategorie",
    date: "2026-07-30",
    current: false,
    items: [
      "Button Results manuell in Manuelle Rangliste umbenannt.",
      "Die manuelle Rangliste verwendet keine Motos/Heats mehr als Eingabebasis.",
      "Alle Teilnehmer einer Kategorie werden in einer einzigen Kachel angezeigt, auch bei mehr als 8 Teilnehmern.",
      "Die Klick-Reihenfolge erzeugt direkt die Rangliste der Kategorie.",
      "Resultate-PDF verwendet danach wie gewohnt die gespeicherte manuelle Rangliste.",
    ],
  },
  {
    version: "v1.13.7",
    title: "Teilnehmer-Excel Export und Import",
    date: "2026-06-09",
    items: [
      "Teilnehmer können aus der Hauptdatenbank als Excel-Datei exportiert werden.",
      "Das Excel enthält eine editierbare Tabelle Teilnehmer und eine geschützte Übersicht Resultate.",
      "Neue Teilnehmer ohne Teilnehmer-ID erhalten beim Re-Import automatisch eine stabile Teilnehmer-ID.",
      "Bestehende Teilnehmer werden über Teilnehmer-ID oder Stammdaten erkannt und zentral aktualisiert.",
      "Resultate, Rennen, Motos, Finals und Gesamtwertung werden beim Excel-Import nicht überschrieben, sondern nur mit den aktualisierten Stammdaten synchronisiert.",
    ],
  },
  {
    version: "v1.13.6",
    title: "Zentrale Teilnehmer-ID und Daten-Synchronisierung",
    date: "2026-06-09",
    items: [
      "Teilnehmerdaten werden beim Bearbeiten über die stabile Teilnehmer-ID synchronisiert.",
      "Änderungen an Name, Startnummer, Jahrgang, Geschlecht, Verein oder Cruiser-Status werden in Hauptdatenbank, Rennen, Motos, Resultaten, Finals und Gesamtwertung übernommen.",
      "Beim Bearbeiten auf der Teilnehmer-Hauptseite und auf der Renn-Teilnehmerseite wird automatisch zum Eingabeformular gescrollt.",
      "Die stabile Teilnehmer-ID wird in der Teilnehmer-Hauptdatenbank und in der Renn-Teilnehmerliste sichtbar angezeigt.",
      "Interne Race-Zuordnungen und Resultat-Verknüpfungen bleiben erhalten, damit bestehende Ranglisten stabil bleiben.",
    ],
  },
  {
    version: "v1.13.5",
    title: "Stabiles Rennen-Löschen und Papierkorb leeren",
    date: "2026-06-09",
    
    items: [
      "Löschen von Rennen/Rennserien weiter stabilisiert: Die Oberfläche wird zuerst vom geöffneten Rennen entkoppelt, bevor lokale Daten gelöscht werden.",
      "Beim Löschen des aktuell geöffneten Rennens wird die Event-ID geleert und zur Startseite gewechselt, damit kein Render mehr auf entfernte Race-Daten zugreift.",
      "Bereinigung von Teilnehmer-, AppData- und localStorage-Daten erfolgt gemeinsam und robuster.",
      "Im Papierkorb gibt es neu den Button Papierkorb leeren, um alle gelöschten Teilnehmer auf einmal endgültig zu entfernen.",
      "Vor dem Leeren des Papierkorbs wird automatisch ein komplettes Sicherheitsbackup erstellt.",
    ],
  },
  {
    version: "v1.13.4",
    title: "Stabiles Löschen von Rennen und Teilnehmerdaten",
    date: "2026-06-09",
    items: [
      "Löschen von Rennen/Rennserien stabilisiert, damit nach dem ersten Klick nicht mehr auf bereits entfernte Daten zugegriffen wird.",
      "Beim Löschen des aktuell geöffneten Rennens wird der Rennstatus zuerst sicher zurückgesetzt und danach zur Startseite gewechselt.",
      "Alle Teilnehmer löschen entfernt Teilnehmer nun endgültig inklusive Papierkorb-Einträgen und zugehörigen Motos, Resultaten, Finals und Gesamtwertungsdaten.",
      "Alte Teilnehmerdaten werden dadurch nicht mehr als bereits vorhanden erkannt, wenn später Teilnehmer importiert oder neu hinzugefügt werden.",
      "Vor dem vollständigen Löschen wird weiterhin automatisch ein komplettes Sicherheitsbackup erstellt.",
    ],
  },
  {
    version: "v1.13.3",
    title: "Import/Export als komplettes App-Backup",
    date: "2026-06-09",
    
    items: [
      "Speichern und Backup exportieren immer die komplette App-Datei mit allen Rennen, Rennserien, Teilnehmern, Resultaten und Einstellungen.",
      "Import/Export wird nur auf der Startseite angezeigt.",
      "Auf Rennseiten gibt es wieder einen Speichern-Button mit derselben kompletten Backup-Export-Funktion.",
      "Ein Import ersetzt die lokalen Daten auf dem Gerät vollständig, damit danach nur die importierten Daten sichtbar sind.",
      "Einzelrennen-/Event-Export-Buttons wurden aus der Oberfläche entfernt, um unvollständige Import-Dateien zu vermeiden.",
    ],
  },
  {
    version: "v1.13.2",
    title: "Alle Teilnehmer gesammelt löschen",
    date: "2026-06-09",
    items: [
      "Teilnehmer-Hauptdatenbank erhält eine Funktion, um alle aktiven Teilnehmer gesammelt in den Papierkorb zu verschieben.",
      "Vor dem Sammellöschen wird automatisch ein Sicherheitsbackup erstellt.",
      "Die Löschung ist bewusst als Papierkorb-Aktion umgesetzt, damit Teilnehmer wiederhergestellt werden können.",
      "Rennlogik, Resultate und Gesamtwertung werden nicht verändert.",
    ],
  },
  {
    version: "v1.13.1",
    title: "Stabile Teilnehmerbearbeitung und Kategorie-Zusammenlegung",
    date: "2026-06-09",
    items: [
      "Beim Bearbeiten von Teilnehmern wird automatisch nach oben zum Eingabefeld gescrollt.",
      "Race-Zuordnungen bleiben beim Bearbeiten erhalten.",
      "Teilnehmer erhalten eine stabile Teilnehmer-ID, damit Resultate und Gesamtwertung verbunden bleiben.",
      "Falls eine Bearbeitung eine neue technische ID erzeugt, werden Resultat-Referenzen auf die neue ID übertragen.",
      "Jede Kategorie kann nun wie Cruiser mit einer anderen Kategorie zusammen starten.",
      "Rangliste und Gesamtwertung bleiben trotz gemeinsamer Starts pro Original-Kategorie getrennt.",
    ],
  },
  {
    version: "v1.13.0",
    date: "02.06.2026",
    title: "Technische Struktur verbessert",
    items: [
      "App-Konfiguration, Version und Datenstruktur-Version in eigene Datei ausgelagert",
      "Release Notes aus App.tsx ausgelagert",
      "Header in eigene Komponente ausgelagert",
      "Zentraler Storage-Wrapper für lokale Browser-Speicherung ergänzt",
      "Backup-Dateien mit App-, Backup- und Datenstruktur-Metadaten erweitert",
      "Import-Prüfung robuster gemacht und Datenmodell-Version für Rennserien ergänzt",
      "Keine Änderung an Rennlogik oder bestehenden gespeicherten Daten",
    ],
  },
  {
    version: "v1.12.9",
    date: "02.06.2026",
    title: "Release Notes auf History-Seite",
    items: [
      "Versionshistorie auf der Seite History / Speicher & Import ergänzt",
      "Release Notes im Stil einer Software-History sichtbar gemacht",
      "Keine Änderung an Speicherlogik, Import/Export, Rennen oder bestehenden Daten",
    ],
  },
  {
    version: "v1.12.8",
    date: "02.06.2026",
    title: "Rennblatt-Buttons bereinigt",
    items: [
      "Button Resultate manuell erstellen in Results manuell umbenannt",
      "Button Speichern im Rennblatt entfernt",
      "Keine Änderung an Rennlogik oder Backup-System",
    ],
  },
  {
    version: "v1.12.7",
    date: "02.06.2026",
    title: "iPad-Bedienung optisch verbessert",
    items: [
      "Buttons vergrössert und Touch-Flächen verbessert",
      "Abstände zwischen Bedienelementen erhöht",
      "Kritische Aktionen farblich klarer markiert",
      "Rennstatus-Anzeigen sichtbarer gemacht",
    ],
  },
  {
    version: "v1.12.6",
    date: "02.06.2026",
    title: "Header-Banner ausgelagert und responsiver gemacht",
    items: [
      "Banner aus App.tsx in src/assets/header-banner.jpg ausgelagert",
      "Header-Kachel responsiver gemacht",
      "Logo im Banner wird weniger stark zugeschnitten",
    ],
  },
  {
    version: "v1.12.5",
    date: "02.06.2026",
    title: "Header-Höhe nachjustiert",
    items: [
      "Kopf-Kachel nochmals höher gemacht",
      "Banner-Zuschnitt reduziert, damit das Logo besser sichtbar ist",
    ],
  },
  {
    version: "v1.12.4",
    date: "02.06.2026",
    title: "Header-Kachel erhöht",
    items: [
      "Kopf-Kachel oben höher gemacht",
      "Banner-Hintergrund beibehalten",
    ],
  },
  {
    version: "v1.12.3",
    date: "02.06.2026",
    title: "Neuer Header-Banner",
    items: [
      "Neuer Banner als Hintergrund der Kopf-Kachel eingebaut",
      "App-Name im Header entfernt",
      "Zielflaggen-Emoji links entfernt",
      "Versionsnummer sichtbar gelassen",
      "Gespeichert-/Backup-Kachel kleiner und unten ausgerichtet",
      "Klick auf Kopf-Kachel führt zurück zur Startseite",
    ],
  },
];
